### ISSUE TITLE
extra delay on no damage caused in fast option.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#225]
Using battle speed on fast make getting hit without damage to cause an extra delay for no reason.
- Boot GT with a ghost pokemon of any kind.
- Decrease enemy cleffa attack stat.
- Let it hit you.
- Have a delay to start of next turn.

**Comment by audinowho** [comment]
this is caused by floating pokemon having a "None" animation that uses the full idle anim instead of taking just the first frame of the idle.  It was set this way so they don't remain motionless in cutscenes.  However, it has resulted in delays in which an entire idle cycle must complete before continuing processing.

**Comment by audinowho** [comment]
https://github.com/RogueCollab/RogueEssence/commit/73b825cc7513c77a8bba26c3c4b92a707d0a966a
