### ISSUE TITLE
PMDO for Linux is running but on black screen using wayland

### ISSUE THREAD

**Issue by PikachuandEevee2000** [audinowho/PMDODump#67]
Hello I discovered this problem when running PMDO but it runs on black screen when using wayland as a windows system but when using X11 the game runs normally
![Captura de pantalla de 2022-03-28 13-35-48](https://user-images.githubusercontent.com/83995523/160457169-fafa4a2e-6094-45ce-a7dd-9beece22e8fb.png)
![Captura de pantalla de 2022-03-28 14-44-29](https://user-images.githubusercontent.com/83995523/160457197-f51d93ac-c871-484f-bce8-430b12096ced.png)
I consider that they solve this problem when launching PMDO 0.6.0 since Ubuntu 22.04 will put wayland by default even with an Nvidia graphics card

**Comment by Xindage** [comment]
I'm also a Linux user (Arch linux) i use KDE as desktop environment, running in both X11 (default) and Wayland, and on my side the game runs fine in both wayland and x11, but there's a major difference, i dont have nvidia card, i'm using nouveau for integrated intel card.
So I think that maybe not exactly the wayland problem, but actually the wayland compatibility with nvidia drivers, if it's not much ask (Because i'm not a programmer, and i dont have skills to really help) you can try setting you driver to nouveau and test if the game still runs black in wayland, if not there's a problem with nvidia instead.

**Comment by rwenable** [comment]
I can run it on arch + wayland + nvidia (so it's **probably** an ubuntu specific configuration thing).
I have heard there are some issues with old versions of the nvidia drivers and wayland.
![good](https://user-images.githubusercontent.com/103006955/161649640-68c7bc0c-8e04-4961-9966-993a989e31be.png)

**Comment by audinowho** [comment]
From further conversation this appears to be an issue affecting not just PMDO but the entire OS.  Based on the current information I am closing this ticket.  @PikachuandEevee2000 but feel free to have it reopened if problems persist after resolving the OS.

**Comment by PikachuandEevee2000** [comment]
Well, actually, since April 2022 I could no longer access Wayland since it freezes the entire operating system, forcing me to use X11. I would have to solve it by asking AskUbuntu before solving what the problem is that it gives me in PMDO.

**Comment by PikachuandEevee2000** [comment]
The issue was mysteriously fixed by upgrading from Ubuntu 21.10 to 22.04 LTS
