### ISSUE TITLE
Reset dungeons is having serious issues.

### ISSUE THREAD

**Issue by Xindage** [audinowho/PMDODump#95]
On the state that reset dungeons is right now, it's very unstable:
If a Pokemon enters it holding a item, no level reset is made, possible making it a easy walk for over leved pokemoms.
Or if nobody is holding a item, Level reset is made, but upon leaving the dungeon all pokemons but the favorites wont get it's levels back, resetting everyone to level 5.

**Comment by audinowho** [comment]
Reset dungeon failing is due to an error with item equip event (specifically, dequip event that fires when calculating loss penalty in the preparation of a failed save file in case the quicksave is lost), fixed in https://github.com/RogueCollab/RogueEssence/commit/ad3efd5bf125ef5b9d3bd462c4f2e6768644b385
Leaving dungeon resetting levels is due to exit-dungeon code re-merging all EXP gained in the dungeon and applying it to the player.  If it hits 100, it triggers an error.  Fix in https://github.com/RogueCollab/RogueEssence/commit/6b9b68d91481506a1c68a916b556b24893414f8d
